add collateral_ratio
pokassun/parrot-monorepo pull request #1
Opened 2021-04-08 04:13 UTC by pokassun

2021-04-08 05:02 UTC, defactojob requested changes

2021-04-08 05:02 UTC, defactojob commented on programs/parrot/src/lib.rs
> +            vault.collateral_ratio = collateral_ratio.to_num();
do we need to store `collateral_ratio`

2021-04-08 05:02 UTC, defactojob commented on programs/parrot/src/lib.rs
> +            vault.debt_amount = fp_total_debt_amount.to_num();
don't truncate `debt_amount`. store u64f64 in `debt_amount` as u128

2021-04-09 01:19 UTC, defactojob commented on programs/parrot/src/lib.rs
> +            if vault_type.liquidation_collateral_ratio > collateral_ratio {
if collateral_ratio > vault_type.liquidation_collateral_ratio {
   return Err(Error::LiquidationOverCollateralized)?;
}

2021-04-09 01:30 UTC, defactojob requested changes

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                let token_price = Fix::from_num(1).div(2);
redundant. in a transaction, the price will stay the same.

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                let repay_collateral_amount = calculate_repay_collateral_amount(
change `calculate_repay_collateral_amount` so it just calculate the inverse.

move `liquidation_penalty` penalty outside.

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                token::transfer(cpi_ctx, repay_collateral_amount.to_num())?;
good point.

let's not transfer directly, but credit the liquidator's vault's `collateral_amount`

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                msg!("burn debt");
liquidator's burn his own debt (like in repay). but instead of decreasing the debt_amount in liquidator's vault, the debt_amount in the borrower's vault is decreased.

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                msg!("burn debt");
and also, the borrower's vault's collateral_amount should decrease by liquidation_collateral_peanalty

2021-04-09 01:30 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                let fp_new_debt = fp_vault_debt_amount - fp_repay_debt_amount;
use checked arithmetic to prevent underflow.

2021-04-09 01:37 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                let repay_collateral_amount = calculate_repay_collateral_amount(
actually this is wrong.

the liquidator should receive:

```
collateral_loss = repay_collateral_amount + liquidation_penalty

vault.collateral_amount -= collateral_loss
```

2021-04-09 03:26 UTC, hayeah commented on programs/parrot/src/lib.rs
> +                fp_repay_debt_amount = fp_vault_debt_amount;
i think there is some dust here.

maybe add a `FIXME` comment for now, and we'll come back to this issue.

2021-04-09 03:33 UTC, defactojob requested changes

2021-04-09 03:33 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                fp_repay_debt_amount = fp_vault_debt_amount;
i think there is some dust here.

maybe add a FIXME comment for now, and we'll come back to this issue.

2021-04-09 03:33 UTC, defactojob commented on programs/parrot/src/lib.rs
> +                * Fix::from_num(vault_type.liquidation_penalty)
let's always use `checked_*` to be safe

2021-04-09 03:33 UTC, defactojob commented on programs/parrot/src/lib.rs
> +            liquidator_vault.debt_amount = fp_liquidator_debt_amount.to_bits();
we should burn `fp_repay_debt_amount` of debt token here, since we shouldn't assume that the liquidator has any collateral in its vault

2021-04-09 06:31 UTC, defactojob requested changes

2021-04-09 06:31 UTC, defactojob commented on programs/parrot/src/lib.rs
>                  .checked_sub(fp_collateral_loss)
this is still wrong. liquidator already burned the debt, and should not have its deb_amount increased.

```
let fp_liquidator_debt_amount = Fix::from_bits(liquidator_vault.debt_amount)
                .checked_add(fp_repay_debt_amount)
                .ok_or(ParrotError::NumberOverflow)?;
            liquidator_vault.debt_amount = fp_liquidator_debt_amount.to_bits();
```

2021-04-09 08:08 UTC, merged